#!/usr/bin/env python3
import os
import sys
import subprocess
import time
import argparse
import hashlib
import json
from pathlib import Path
import math

# Try to use PIL for pyramid generation
try:
    from PIL import Image
except ImportError:
    print("Installing Pillow for image processing...")
    subprocess.run(["pip3", "install", "Pillow"], check=True)
    from PIL import Image

Z_MAX = 13
Z_MIN = 6
TILE_SIZE = 256
QGIS_EQUATOR = 2 ** (Z_MAX - 1)  # 4096 at z=13

def get_world_bounds(mapper_exe, world_path, colors_file):
    """ Executes minetestmapper to get the absolute boundaries of the generated world """
    cmd = [mapper_exe, "--extent", "--input", world_path, "--colors", colors_file]
    
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        # Parse output like: -640:-144+880+896
        output = result.stdout.strip()
        if not output: output = result.stderr.strip()
        
        # Example matcher: -640:-144+880+896
        import re
        m = re.search(r"([-0-9]+):([-0-9]+)\+([0-9]+)\+([0-9]+)", output)
        if m:
            left = int(m.group(1))
            bottom = int(m.group(2))
            width = int(m.group(3))
            height = int(m.group(4))
            return left, bottom, width, height
        else:
            print(f"Warning: Could not parse extent: {output}")
            return -1024, -1024, 2048, 2048
    except subprocess.CalledProcessError as e:
        print(f"Error checking bounds: {e.stderr}")
        return -1024, -1024, 2048, 2048

def file_hash(filepath):
    """ Quick MD5 hash to determine if tile actually changed visually """
    if not os.path.exists(filepath): return ""
    with open(filepath, 'rb') as f:
        return hashlib.md5(f.read()).hexdigest()

def generate_base_tiles(mapper_exe, world_path, output_dir, colors_file, incremental=True):
    """ Generates Z_MAX tiles natively bounding mathematically to EPSG:3857 chunks """
    left, bottom, width, height = get_world_bounds(mapper_exe, world_path, colors_file)
    print(f"World bounds detected: L:{left} B:{bottom} W:{width} H:{height}")
    
    # Calculate min and max tile index at Z=13
    # game_x = qx - 4096 => qx = game_x + 4096
    # game_y = 4096 - qy => qy = 4096 - game_y
    # game coordinates are roughly nodes / 256
    
    start_qgis_x = math.floor(left / TILE_SIZE) + QGIS_EQUATOR
    end_qgis_x = math.ceil((left + width) / TILE_SIZE) + QGIS_EQUATOR
    
    start_qgis_y = QGIS_EQUATOR - math.ceil((bottom + height) / TILE_SIZE)
    end_qgis_y = QGIS_EQUATOR - math.floor(bottom / TILE_SIZE)
    
    print(f"Slippy Grid: X[{start_qgis_x} TO {end_qgis_x}] Y[{start_qgis_y} TO {end_qgis_y}]")
    
    tiles_updated = 0
    z13_dir = Path(output_dir) / str(Z_MAX)
    
    for qx in range(start_qgis_x, end_qgis_x + 1):
        for qy in range(start_qgis_y, end_qgis_y + 1):
            
            # Map QGIS Slippy back to Cartesian game bounds
            game_x = qx - QGIS_EQUATOR
            game_y = QGIS_EQUATOR - qy
            
            t_left = game_x * TILE_SIZE
            t_bottom = (game_y - 1) * TILE_SIZE # Bottom of the tile box
            
            x_dir = z13_dir / str(qx)
            x_dir.mkdir(parents=True, exist_ok=True)
            tile_path = x_dir / f"{qy}.png"
            temp_path = x_dir / f"{qy}_temp.png"
            
            # Only generate chunks that could intersect the world
            cmd = [
                mapper_exe,
                "--input", world_path,
                "--output", str(temp_path),
                "--geometry", f"{t_left}:{t_bottom}+{TILE_SIZE}+{TILE_SIZE}",
                "--colors", colors_file,
                "--bgcolor", "#00000000" # Fully transparent background for Web Mercator oceans
            ]
            
            subprocess.run(cmd, capture_output=True)
            
            if temp_path.exists():
                new_hash = file_hash(temp_path)
                old_hash = file_hash(tile_path)
                
                # Check for completely empty/transparent png generated by minetestmapper
                # (A transparent 256x256 png is usually ~100-200 bytes)
                if temp_path.stat().st_size < 300:
                    temp_path.unlink()
                    if tile_path.exists(): tile_path.unlink() # Cleanup old voids
                    continue
                
                if not incremental or new_hash != old_hash:
                    os.replace(temp_path, tile_path)
                    tiles_updated += 1
                else:
                    temp_path.unlink() # no change

    print(f"Base Tile Layer (Z={Z_MAX}) updated. {tiles_updated} tiles refreshed.")
    return tiles_updated > 0

def build_zoom_pyramid(output_dir):
    """ Iteratively generates smaller zoom levels by merging 2x2 blocks of higher zoom tiles """
    for z in range(Z_MAX - 1, Z_MIN - 1, -1):
        print(f"Building zoom pyramid Z={z}...")
        z_high = z + 1
        high_dir = Path(output_dir) / str(z_high)
        z_dir = Path(output_dir) / str(z)
        
        if not high_dir.exists(): continue
        
        # Find all X directories
        x_dirs = [d for d in high_dir.iterdir() if d.is_dir()]
        updates = 0
        
        # Calculate new lower-zoom tile indices based on high-zoom chunks available
        processed_pairs = set()
        
        for qx_dir in x_dirs:
            hx = int(qx_dir.name)
            for hy_file in qx_dir.glob("*.png"):
                hy = int(hy_file.stem)
                
                # 2x2 grid math
                lx, ly = hx // 2, hy // 2
                if (lx, ly) in processed_pairs: continue
                processed_pairs.add((lx, ly))
                
                out_x_dir = z_dir / str(lx)
                out_x_dir.mkdir(parents=True, exist_ok=True)
                out_tile = out_x_dir / f"{ly}.png"
                
                # Create merged bounding box
                dest_img = Image.new("RGBA", (TILE_SIZE * 2, TILE_SIZE * 2), (0,0,0,0))
                
                has_content = False
                for ox in (0, 1):
                    for oy in (0, 1):
                        src_x, src_y = lx * 2 + ox, ly * 2 + oy
                        src_path = high_dir / str(src_x) / f"{src_y}.png"
                        if src_path.exists():
                            with Image.open(src_path) as src:
                                dest_img.paste(src, (ox * TILE_SIZE, oy * TILE_SIZE))
                                has_content = True
                                
                if has_content:
                    # Scale down to 256x256
                    scaled = dest_img.resize((TILE_SIZE, TILE_SIZE), Image.Resampling.LANCZOS)
                    scaled.save(out_tile, "PNG")
                    updates += 1
                    
        print(f"Z={z} completed. {updates} tiles generated.")
        
def run_incremental_daemon(mapper_exe, world_path, output_dir, colors_file):
    print("Initiating Continuous Map Tile Daemon...")
    while True:
        try:
            print("\n--- Starting Generation Cycle ---")
            changed = generate_base_tiles(mapper_exe, world_path, output_dir, colors_file)
            if changed:
                build_zoom_pyramid(output_dir)
            print("Cycle completed. Sleeping for 30s...")
            time.sleep(30)
        except KeyboardInterrupt:
            print("Daemon stopped.")
            break
        except Exception as e:
            print(f"Error in cycle: {e}")
            time.sleep(10)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Incremental Minetest-to-QGIS Tiler")
    parser.add_argument("--world", required=True, help="Path to Minetest world directory")
    parser.add_argument("--mapper", required=True, help="Path to minetestmapper executable")
    parser.add_argument("--colors", required=True, help="Path to colors.txt")
    parser.add_argument("--output", required=True, help="Tiles output directory")
    parser.add_argument("--daemon", action="store_true", help="Run continuously")
    
    args = parser.parse_args()
    
    if args.daemon:
        run_incremental_daemon(args.mapper, args.world, args.output, args.colors)
    else:
        changed = generate_base_tiles(args.mapper, args.world, args.output, args.colors, incremental=False)
        build_zoom_pyramid(args.output)
